# Generated by Django 4.1.6 on 2023-03-05 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallermecanica', '0002_cliente_tipoidentificacion_tipovehiculo_vehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('sueldo', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=300)),
                ('apellido', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=300)),
                ('direccion', models.CharField(max_length=300)),
                ('idciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallermecanica.ciudad')),
                ('idespecialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallermecanica.especialidad')),
                ('idtipoidentificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallermecanica.tipoidentificacion')),
            ],
        ),
    ]
