# Generated by Django 4.1.6 on 2023-03-05 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallermecanica', '0003_especialidad_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fechaingreso',
            field=models.DateField(default=datetime.datetime(2023, 3, 5, 0, 14, 18, 418877)),
        ),
    ]
