# Generated by Django 4.1.6 on 2023-03-05 10:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallermecanica', '0004_empleado_fechaingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fechaingreso',
            field=models.DateField(default=datetime.datetime(2023, 3, 5, 5, 28, 57, 152540)),
        ),
        migrations.CreateModel(
            name='asignarvehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehiculoasignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallermecanica.vehiculo')),
            ],
        ),
    ]
