# Generated by Django 4.1.6 on 2023-03-05 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallermecanica', '0005_alter_empleado_fechaingreso_asignarvehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fechaingreso',
            field=models.DateField(default=datetime.datetime(2023, 3, 5, 5, 30, 50, 146573)),
        ),
    ]
