# Generated by Django 4.1.6 on 2023-03-05 11:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallermecanica', '0006_alter_empleado_fechaingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignarvehiculo',
            name='empleadovehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tallermecanica.empleado'),
        ),
        migrations.AddField(
            model_name='asignarvehiculo',
            name='fechasignacion',
            field=models.DateField(default=datetime.datetime(2023, 3, 5, 6, 3, 43, 137110)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaingreso',
            field=models.DateField(default=datetime.datetime(2023, 3, 5, 6, 3, 43, 137110)),
        ),
    ]
