# Generated by Django 4.1.6 on 2023-03-16 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallermecanica', '0007_asignarvehiculo_empleadovehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=300)),
                ('clave', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='asignarvehiculo',
            name='fechasignacion',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 18, 5, 22, 907655)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaingreso',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 18, 5, 22, 903664)),
        ),
    ]
